#!/bin/bash

CURRENT=$(pwd)
while [ $CURRENT != '/' ]
do
    if [ -e .git ]; then
        if [ -x "$CURRENT/glue/gonk-ics/out/host/linux-x86/bin/fastboot" ]; then
            CURRENT="$CURRENT/glue/gonk-ics/out/host/linux-x86/bin/fastboot"
            break
        fi

        if [ -x "$CURRENT/glue/gonk/out/host/linux-x86/bin/fastboot" ]; then
            CURRENT="$CURRENT/glue/gonk/out/host/linux-x86/bin/fastboot"
            break
        fi

        if [ -x "$CURRENT/out/host/linux-x86/bin/fastboot" ]; then
            CURRENT="$CURRENT/out/host/linux-x86/bin/fastboot"
            break
        fi
    fi

    CURRENT=$(dirname $CURRENT)
done

if [ $CURRENT == '/' ]; then
    CURRENT='/build/2B2G-otoro/out/host/linux-x86/bin/fastboot'
fi

if [ ! -x $CURRENT ]; then
    echo "Unable to find fastboot"
    exit 1
fi

$CURRENT $*
exit 0
