#!/bin/sh

# Usage: gdbwait <program name>
# Attaches to the oldest version of <program name>, busy-waiting until it
# starts.

progstr=$1
progpid=`pgrep -o $progstr`
while [ "$progpid" = "" ]; do
  progpid=`pgrep -o $progstr`
done
gdb -p $progpid
