#!/usr/bin/python

import sys
import os

try:
    makeflags = os.environ['MAKEFLAGS']
except:
    makeflags = '-s -j 8'

cur = 1
path = "dbg-obj"

# Synatxes:
# jsmake                # builds dbg-obj
# jsmake -directory     # builds directory-obj
# jsmake target         # builds dbg-obj <target>
# jsmake -directory target # builds directory-obj <target>
# jsmake -- -make-flag  # builds dbg-obj -make-flag
# jsmake -              # builds dbg-obj <->
if len(sys.argv) > 1:
    try:
        if sys.argv[cur][0] == '-':
            if sys.argv[cur][1] != '-':
                path = sys.argv[cur][1:] + '-obj'
            cur = cur + 1
    except:
        pass

if not os.path.isdir(path):
    print >> sys.stderr, "Wanted directory isn't a directory"
    sys.exit(1)

# Figure out if we should run configure.
configure = True
if os.path.isfile('configure'):
    intime = os.path.getmtime('configure.in')
    if intime <= os.path.getmtime('configure'):
        status = os.path.join(path, 'config.status')
        if os.path.isfile(status) and os.path.getmtime(status) >= intime:
            configure = False

if configure:
    os.system("cd %s && ./configure" % path)

os.system("""make %s -C %s %s 2>&1 | sed -u -e 's|^\(\.\./\)*||'""" % \
        (makeflags, path, ' '.join(sys.argv[cur:])))
