#!/bin/sh

# Helper script to find a mach executable in either the current directory or a
# mozilla sibling directory. Also forces Python 2 (thanks, Arch Linux!).

MACH=''
if [ -x ./mach ]; then
    MACH='./mach'
elif [ -x ../mozilla/mach ]; then
    MACH='../mozilla/mach'
else
    echo "Error: no (executable) 'mach' in current directory" >&2
    exit 1
fi

python2 $MACH $@
