#!/bin/sh

# Finds and removes temporary backup files, core files, or patch reject files
# from the current directory (but without descending into git or hg metadata
# directories).

find . \( -name .git -or -name .hg \) -prune -or \
       \( -name '.#*' -or \
          -name '#*#' -or \
          -name '*~'  -or \
          -name 'core.[0-9]*' -or \
          -name 'vgcore.[0-9]*' -or \
          -name 'core' -or \
          -name '*.orig' -or \
          -name '*.rej' \
       \) -and -type f \
       -print -exec rm '{}' \;
