#!/bin/sh

find . \( -name .git -or -name .hg -or -name testing -or -name extensions \) -prune -or \
       \( -name '.#*' -or \
          -name '#*#' -or \
          -name '*~'  -or \
          -name 'core.[0-9]*' -or \
          -name 'vgcore.[0-9]*' -or \
          -name 'core' -or \
          -name '*.orig' -or \
          -name '*.rej' \
       \) -and -type f \
       -print -exec rm '{}' \;
